### ISSUE TITLE
blog seems to be offline

### ISSUE THREAD

**Issue by ninrod** [aaronbieber/blog#1]
Hi @aaronbieber, your blog is offline. 

Awesome posts by the way. I'm a vim expatriate just because of that youtube video of yours.

thanks!

**Comment by aaronbieber** [comment]
Looks online to me, and I do use a monitoring service as well. Thanks for
the kind words, I really appreciate that!

**Comment by ninrod** [comment]
I'm in south america, maybe there's a route problem. 

Good thing that I have access to the markdown posts! Trying to setup my org-agenda

<img width="377" alt="screen shot 2017-02-03 at 09 51 30" src="https://cloud.githubusercontent.com/assets/8352747/22590458/72ab61a8-e9f6-11e6-904e-e02b23169ff0.png">

**Comment by aaronbieber** [comment]
Could be. Also try https directly, as an experiment. I recently changed
over to SSL everywhere. Montastic confirms that the blog has been online
for at least a few weeks.

If you install the Jekyll Ruby gem you can build the site and view it
locally. Follow the instructions on Jekyll's website.

**Comment by ninrod** [comment]
that's it! https sealed the deal! thank you!

**Comment by aaronbieber** [comment]
Weird okay, good to know. The non-https site should redirect and does for
me and my monitoring service. Hopefully this is some fluke from your
specific location.

**Comment by aaronbieber** [comment]
I discovered that my HTTPS redirect server rules were not yet configured for all of my domains, which is why the HTTP URL was not properly redirecting to the HTTPS site. This should actually be resolved now.

**Comment by ninrod** [comment]
Awesome that you were able to fix the issue aaron. And thanks again for all the emacs information you are sharing!
